### PR TITLE
Added tests for a guest user to see the list page when there are no torrents in the index

### LINKED ISSUE #310: E2E tests: List page should be displayed to a guest user when there are no torrents in the index
Parent issue: https://github.com/torrust/torrust-index-gui/issues/148

E2E test for displaying the list page with no torrents for a guest user.

### PR DESCRIPTION
**Pull request by mario-nt**
Resolves #310.

### CODE REVIEW

**Comment by mario-nt** [comment]
[`https://github.com/torrust/torrust-index-gui/blob/b1e9ab6b3a7f89295d22781b73542c21fe176b74/cypress/e2e/contexts/torrent/specs/list/no_torrents_to_display.cy.ts#L1-L14`](https://github.com/torrust/torrust-index-gui/blob/b1e9ab6b3a7f89295d22781b73542c21fe176b74/cypress/e2e/contexts/torrent/specs/list/no_torrents_to_display.cy.ts#L1-L14)

```JS
import { baseURL } from "nuxt/dist/core/runtime/nitro/paths";


describe("A guest user", () => {
  before(() => {
    // Deletes all torrents and their related info from the database so the test can pass
    cy.clear_torrent_info_from_database();
  });


  it("Should be able to see the list page when there are no torrents", () => {
    cy.visit("/torrents");
    cy.url().should("match", /\/torrents$/);
    cy.get("[data-cy=\"no-results-element\"]").invoke("text").should("match", /No results./i);
  });
});
```

@josecelano Do you think is worth implementing the test with an admin/logged in user too?, I don't think it would change the result of the test, but wanted a second opinion.

**Comment by josecelano** [comment]
> [`https://github.com/torrust/torrust-index-gui/blob/b1e9ab6b3a7f89295d22781b73542c21fe176b74/cypress/e2e/contexts/torrent/specs/list/no_torrents_to_display.cy.ts#L1-L14`](https://github.com/torrust/torrust-index-gui/blob/b1e9ab6b3a7f89295d22781b73542c21fe176b74/cypress/e2e/contexts/torrent/specs/list/no_torrents_to_display.cy.ts#L1-L14)
> 
> ```js
> import { baseURL } from "nuxt/dist/core/runtime/nitro/paths";
> 
> 
> describe("A guest user", () => {
>   before(() => {
>     // Deletes all torrents and their related info from the database so the test can pass
>     cy.clear_torrent_info_from_database();
>   });
> 
> 
>   it("Should be able to see the list page when there are no torrents", () => {
>     cy.visit("/torrents");
>     cy.url().should("match", /\/torrents$/);
>     cy.get("[data-cy=\"no-results-element\"]").invoke("text").should("match", /No results./i);
>   });
> });
> ```
> 
> @josecelano Do you think is worth implementing the test with an admin/logged in user too?, I don't think it would change the result of the test, but wanted a second opinion.

I always have doubts about E2E tests. The other two tests seem more like a test for the permissions. I guess here we are testing the feature that users see a friendly message when there are no torrents, not that users can see this content. Since we are using the role with the lowest permissions, I think it's ok.

Maybe we can change the describe section `describe("A guest user", () => {...}` to `describe("Users", () => {...}` to avoid misunderstandings. People can think only guests can see that message. Even if the test is using a concrete role.

**Comment by mario-nt** [comment]
@josecelano I really like the idea of using "Users", I will refactor that part.

**Comment by mario-nt** [comment]
@josecelano Ready for review

**Review by josecelano — APPROVED** [review]

**Comment by josecelano** [comment]
ACK 6d6806de33440b474dcd1b7042d59dc89f044e65

**Pull request merged**
