### PR TITLE
Add option to close banner

### PR DESCRIPTION
**Pull request by mario-nt**
Banner could use a button to allow the user to close it.

### CODE REVIEW

**Review by josecelano — CHANGES_REQUESTED** [review]
HI @mario-nt 

image

I don't know if that was the intended behavior but the text "Read our Terms" is aligned to the right next to the close X.

**Comment by mario-nt** [comment]
@josecelano With my screen resolution (2560x1600) and scale set to 100% it looks like this (which is the intended behaviour):

image

But if I change the resolution or zoom in it aligns with the text, I will take another look.

**Review by josecelano — CHANGES_REQUESTED** [review]
Hi @mario-nt I still see the same:

image

image

**Comment by mario-nt** [comment]
@josecelano Hi!, I didn't notice that the layout of the text was changed when I added the x button to close the banner, I will fix that too.

**Comment by mario-nt** [comment]
Hi @da2ce7, do you like the new layout of the close button or you prefer to have it on the right corner of the banner? I leave a few screenshots so you can see it without getting the branch:

**Screenshot #1**

image

**Screenshot #2**

image

**Screenshot #3**

image

**Screenshot #4**

image

**Comment by josecelano** [comment]
ACK 37d146632faa0248c04cb50f44c866ea416542c7

**Review by josecelano — APPROVED** [review]

**Pull request merged**
