### PR TITLE
Light theme support.

### LINKED ISSUE #421: Light and auto theme support.
Right now we are only using a dark theme for the GUI, it would be a nice addition to add a light/auto theme so users can customize the look of the app based on their preferences.

The Torrust website is a good example of this: https://torrust.com/

- [x] Dark mode toggle
- [x] Auto/System mode toggle
- [x] Improve light theme readability
- [x] Responsive design support
- [x] Buttons hover animation
- ~~[] Buttons transition animation [POSTPONED]~~

### PR DESCRIPTION
**Pull request by mario-nt**
Resolves #421.

### CODE REVIEW

**Comment by mario-nt** [comment]
@josecelano Ready for review

**Review by josecelano — APPROVED** [review]
And God said, “Let there be light,” and there was light.

Awesome @mario-nt! good job!

I also like the changes in fonts, It makes all more clean and beatiful.

**Comment by josecelano** [comment]
ACK 4ee97025cbcec923e19315734429962d693dac6d

**Comment by mario-nt** [comment]
> And God said, “Let there be light,” and there was light.
> 
> Awesome @mario-nt! good job!
> 
> I also like the changes in fonts, It makes all more clean and beatiful.

Thanks!, I really wanted to implement this one :)

**Pull request merged**
