### PR TITLE
Fix browser console warning: ` Incorrect use of label for=FORM_ELEMENT`

### LINKED ISSUE #198: Fix browser console warning: ` Incorrect use of label for=FORM_ELEMENT`
Parent issue: https://github.com/torrust/torrust-index-frontend/issues/96

image

### PR DESCRIPTION
**Pull request by Wolfremium13**
This is a work-in-progress pull request that aims to clear the runtime-errors and warnings in the frontend.

For now we have 2 left, still pending to look further ⬇
image

### CODE REVIEW

**Comment by da2ce7** [comment]
@Wolfremium13 Great First Pull request. I have made some basic formatting changes to the pull request to make it more clear.  Will review after you have cleared all the warnings.

**Comment by Wolfremium13** [comment]
I'm looking further inside the [problem](navigator.userAgent) but I see that it didn't appear in the code any kind of usage of the userAgent. Looking at the compiled code with the error I saw this:
```
    const isNavigatorDefined = typeof navigator !== "undefined";
    const userAgent = isNavigatorDefined
        ? navigator.userAgentData &&
          Array.isArray(navigator.userAgentData.brands)
            ? navigator.userAgentData.brands
                  .map(
                      (brand) => `${brand.brand.toLowerCase()} ${brand.version}`
                  )
                  .join(" ")
            : navigator.userAgent.toLowerCase()
        : "some useragent";
    const platform = isNavigatorDefined
        ? navigator.userAgentData &&
          typeof navigator.userAgentData.platform === "string"
            ? navigator.userAgentData.platform.toLowerCase()
            : navigator.platform.toLowerCase()
        : "some platform";
    userAgent.includes("vivaldi");
    userAgent.includes("yabrowser");
    userAgent.includes("opr") || userAgent.includes("opera");
    userAgent.includes("edg");
    platform.startsWith("win");
    platform.startsWith("mac");
    isNavigatorDefined && navigator.userAgentData
        ? navigator.userAgentData.mobile
        : userAgent.includes("mobile");
```
We are encountering the error because the React Developer Tools Chrome extension is using both the old and the new versions. If I disable it now, the error disappears.
image

**Comment by josecelano** [comment]
> I'm looking further inside the [problem](navigator.userAgent) but I see that it didn't appear in the code any kind of usage of the userAgent. Looking at the compiled code with the error I saw this:
> 
> ```
>     const isNavigatorDefined = typeof navigator !== "undefined";
>     const userAgent = isNavigatorDefined
>         ? navigator.userAgentData &&
>           Array.isArray(navigator.userAgentData.brands)
>             ? navigator.userAgentData.brands
>                   .map(
>                       (brand) => `${brand.brand.toLowerCase()} ${brand.version}`
>                   )
>                   .join(" ")
>             : navigator.userAgent.toLowerCase()
>         : "some useragent";
>     const platform = isNavigatorDefined
>         ? navigator.userAgentData &&
>           typeof navigator.userAgentData.platform === "string"
>             ? navigator.userAgentData.platform.toLowerCase()
>             : navigator.platform.toLowerCase()
>         : "some platform";
>     userAgent.includes("vivaldi");
>     userAgent.includes("yabrowser");
>     userAgent.includes("opr") || userAgent.includes("opera");
>     userAgent.includes("edg");
>     platform.startsWith("win");
>     platform.startsWith("mac");
>     isNavigatorDefined && navigator.userAgentData
>         ? navigator.userAgentData.mobile
>         : userAgent.includes("mobile");
> ```
> 
> We are encountering the error because the React Developer Tools Chrome extension is using both the old and the new versions. If I disable it now, the error disappears. image

Hi @Wolfremium13 thank you for your PR. 

Regarding the issue "Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform". I had the same problem as you. Some extensions need to be updated for the  [Chrome User-Agent reduction](https://developer.chrome.com/docs/privacy-sandbox/user-agent/).

In my case:

- [Vue dev tools](https://devtools.vuejs.org/guide/installation.html): see https://github.com/vuejs/devtools/issues/1599 and https://github.com/vuejs/devtools/issues/1841
- [JSON Viewer ](https://github.com/tulios/json-viewer)

But after disabling those extensions, I found the same problem in this file:

`http://localhost:3000/_nuxt/node_modules/.cache/vite/client/deps/chunk-BVQHDTV7.js?v=1466fdea`

It seems to be a pretty common warning: https://github.com/search?q=Chrome+User-Agent+reduction&type=issues

So I guess we can ignore it for now.

Regarding the other errors [I mentioned on the issue](https://github.com/torrust/torrust-index-frontend/issues/96#issuecomment-1608929470), for some reason, I can't reproduce them anymore with the develop branch:

image

Now I only see the one about [Chrome User-Agent reduction](https://developer.chrome.com/docs/privacy-sandbox/user-agent/).

I suppose this PR fixes only the incorrect use of `<label for=FORM_ELEMENT>`, doesn't it?

image

Could you confirm that you can still see the rest of the errors?

Maybe we can create a new subtask for the issue  https://github.com/torrust/torrust-index-frontend/issues/96 and link this PR to the new issue so we can merge it.

**Comment by Wolfremium13** [comment]
Hello now I see this problem `Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform` after update to this version `Chrome version 115.0.5790.98 (Official Build) (64-bit)` at the same chunk file (all extensions are disabled). 

> I suppose this PR fixes only the incorrect use of <label for=FORM_ELEMENT>, doesn't it?

Yes this PR only fixes this error that's the one that appears on my console at the begining.

I checkout to the branch [Wolfremium13:kevin-issue-96-clean-browser-issues](https://github.com/Wolfremium13/torrust-index-frontend/tree/kevin-issue-96-clean-browser-issues) but I only saw this issue:
image

I cannot see the other errors you had in the console, maybe I need something more to have a look at this errors?

**Comment by josecelano** [comment]
> Hello now I see this problem `Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform` after update to this version `Chrome version 115.0.5790.98 (Official Build) (64-bit)` at the same chunk file (all extensions are disabled).
> 
> > I suppose this PR fixes only the incorrect use of , doesn't it?
> 
> Yes this PR only fixes this error that's the one that appears on my console at the begining.
> 
> I checkout to the branch [Wolfremium13:kevin-issue-96-clean-browser-issues](https://github.com/Wolfremium13/torrust-index-frontend/tree/kevin-issue-96-clean-browser-issues) but I only saw this issue: image
> 
> I cannot see the other errors you had in the console, maybe I need something more to have a look at this errors?

Hi @Wolfremium13 I think we can merge the PR. I've linked the PR to a new issue https://github.com/torrust/torrust-index-frontend/issues/198. We can ignore the "navigator" warning for now since it's now a problem in our code. I guess the dependency that is using it will update it. I would open an issue if I knew the repo that is generating the file:

`http://localhost:3000/_nuxt/node_modules/.cache/vite/client/deps/chunk-BVQHDTV7.js?v=5420e74f`

**Pull request merged**
