### PR TITLE
Show torrent comment on torrent details page

### LINKED ISSUE #277: Show torrent `comment` on torrent details page
The torrent `comment` [field has been stored in the database](https://github.com/torrust/torrust-index-backend/issues/302). And it's included in API responses.

We should show it on the details page.

### PR DESCRIPTION
**Pull request by mario-nt**
Resolves #277.

### CODE REVIEW

**Review by josecelano — APPROVED** [review]

**Comment by josecelano** [comment]
Hi @mario-nt it looks good. If you change the commit message I can merge it.

**Comment by mario-nt** [comment]
> Hi @mario-nt it looks good. If you change the commit message I can merge it.

Nice, once we update the types and API lib packages on NPM, I will update the package.json file and write the final commit message so you can merge the PR.

**Comment by josecelano** [comment]
> > Hi @mario-nt it looks good. If you change the commit message I can merge it.
> 
> Nice, once we update the types and API lib packages on NPM, I will update the package.json file and write the final commit message so you can merge the PR.

Hi @mario-nt, I've done it. I've published the `1.0.0-alpha.3` version for both packages.

**Comment by mario-nt** [comment]
Updated dependencies and tests OK, ready for review and merging. @josecelano

**Review by josecelano — APPROVED** [review]

**Comment by josecelano** [comment]
ACK ce5bd32cf293ec2fdc05410decc0f02389229a73

**Pull request merged**
