### PR TITLE
New static page with terms

### LINKED ISSUE #617: New static page: Usage Policies and Content Restrictions
Parent issue: https://github.com/torrust/torrust-index-gui/issues/614

**Title:** Usage Policies and Content Restrictions

**Content:**  
"Our software is designed to support the distribution of legal, authorized content only. Users may only upload or share files that fall under the following categories:

- **Open-Source Licenses:** Content licensed under recognized open-source licenses, allowing for free distribution and modification.
- **Creative Commons Licenses:** Content released under Creative Commons licenses that permit sharing and distribution.
- **Public Domain:** Content that is free of copyright restrictions and available for public use.

**Prohibited Content:** Any content that infringes copyright, is subject to copyright protection, or is illegal under applicable laws is strictly prohibited. This includes but is not limited to copyrighted movies, music, software, books, and any other media.

**Enforcement:** We reserve the right to remove any content that does not comply with these policies without notice. We may also take additional steps, including reporting violations to the relevant authorities, if necessary."

### PR DESCRIPTION
**Pull request by josecelano**
Depends on:

- https://github.com/torrust/torrust-index-types-lib/pull/25
- https://github.com/torrust/torrust-index/pull/731

URL: http://localhost:3000/terms

It also adds a link in the footer. The page content is loaded in markdown format from the API (settings->website).

### CODE REVIEW

**Comment by josecelano** [comment]
It looks like:

image

**Review by cgbosse — APPROVED** [review]
ACK 0d92346f3954394b2d17cfe62123ca164a8d8e64

**Comment by josecelano** [comment]
ACK 367f420dd298f45087bead313183aff3810946d9

**Comment by josecelano** [comment]
> ACK [0d92346](https://github.com/torrust/torrust-index-gui/commit/0d92346f3954394b2d17cfe62123ca164a8d8e64)

The commit changed because the PR was still a draft. We use ACK only when the PR is ready to merge.

**Pull request merged**
