### PR TITLE
ci: codeowners and sync labels

### PR DESCRIPTION
**Pull request by da2ce7**

### CODE REVIEW

**Comment by da2ce7** [comment]
ACK 66679c739f66b03c526cf35a72a0d2aa3fd322f0

**Comment by josecelano** [comment]
Hi @da2ce7, what's the purpose of the https://github.com/torrust/torrust-index-gui/blob/develop/.github/labels.json file? Just to keep the history of labels?

**Comment by da2ce7** [comment]
@josecelano Hello Jose.

The `labels.json` file defines the labels. When it is updated, the labels for the project are (should test this) automatically update via the `labels.yaml` workflow.

**Comment by josecelano** [comment]
> @josecelano Hello Jose.
> 
> The `labels.json` file defines the labels. When it is updated, the labels for the project are (should test this) automatically update via the `labels.yaml` workflow.

Yes, I understand, but why do you want to update the labels from the code? Is it because you can easily apply the same labels to other repos just by overwriting the `labels.json`?

**Pull request merged**
