### PR TITLE
Force accept agreement before uploading

### LINKED ISSUE #622: Add the "legal checkbox" to the upload torrent form
Parent issue: https://github.com/torrust/torrust-index-gui/issues/614
Relates to: https://github.com/torrust/torrust-index/issues/732

Add a new input check box in the upload form that the user must check to enable uploading the torrent.

Checkbox Text: "I confirm that the content I am uploading is authorized, and I have read and agree to the [Usage Policies](https://github.com/torrust/torrust-index-gui/issues/link-to-policies)."

### Upload form

image

### PR DESCRIPTION
**Pull request by josecelano**
I added a new checkbox to force users to accept the terms and conditions before uploading a torrent.

### CODE REVIEW

**Comment by josecelano** [comment]
image

**Comment by josecelano** [comment]
The link should look like:

image

To make it clear, it's a link, but the general style for links in the app is set to not use text-decoration.

**Comment by josecelano** [comment]
ACK e99245358763ccb54519d4dee5d713e0e05af1ca

**Comment by da2ce7** [comment]
"I comprehend and agree with this index's usage and content policy and that this upload is in full compliance and that this upload is a meaningful contribution according to the sprit and goals this index."

**Comment by josecelano** [comment]
> "I comprehend and agree with this index's usage and content policy and that this upload is in full compliance and that this upload is a meaningful contribution according to the sprit and goals this index."

https://github.com/torrust/torrust-index/issues/732

**Review by cgbosse — APPROVED** [review]
It looks good to me.

**Comment by cgbosse** [comment]
> "I comprehend and agree with this index's usage and content policy and that this upload is in full compliance and that this upload is a meaningful contribution according to the sprit and goals this index."

I think that this may be a little overkill.

**I propose instead:** 

"I have read and agree with the Usage Policies and Content Restrictions."

**Comment by josecelano** [comment]
> > "I comprehend and agree with this index's usage and content policy and that this upload is in full compliance and that this upload is a meaningful contribution according to the sprit and goals this index."
> 
> I think that this may be a little overkill.
> 
> **I propose instead:**
> 
> "I have read and agree with the Usage Policies and Content Restrictions."

Hi @cgbosse, I've opened a new issue because that's a change we have to make to the Index. In fact, It's only the default value. You can override it with a configuration value:

https://github.com/torrust/torrust-index/blob/develop/tests/fixtures/default_configuration.toml#L15

```toml
[website.terms.upload]
content_upload_agreement = """I confirm that the content I am uploading is authorized, and I have read and agree to the terms."""
```

**Comment by josecelano** [comment]
ACK a6ee38f5a51a53cc9d002ac88ba9b0168bd19c0f

**Pull request merged**
